---
title: "Research Projects"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Job Market Paper 

[Party Lines or Voter Preferences? Explaining Political Realignment](PartyLines_NLM.pdf).  <br />
&nbsp;&nbsp;&nbsp; Awarded Best Student Work - [IPUMS Spatial 2023 ](https://www.ipums.org/impact/ipums-research-award?utm_source=IPUMS+Emails&utm_campaign=1d9161f8c5-EMAIL_CAMPAIGN_2019_05_31_07_13_COPY_01&utm_medium=email&utm_term=0_a679127ff0-1d9161f8c5-21864473)

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
This paper estimates a political equilibrium model to disentangle demand factors (voters) from supply factors (politicians) in shaping political outcomes, focusing on the recent realignment of blue-collar voters away from left-wing parties. I jointly evaluate the impact of changes in voter preferences and voter demographics (demand side) and party positions and party discipline (supply side) on voters’ partisan realignment in U.S. House elections between 2000 and 2020. To measure candidate ideological positioning, I estimate a multimodal text-and-survey model from campaign websites. To estimate voter preferences, I build a new panel of precinct-level election results (N=1.3 million), which allows me to exploit congressional districts' border discontinuities for identification. The paper ultimately identifies parties’ stronger polarization on cultural issues compared to economic issues as the main driver of voters’ partisan realignment. In contrast, shifts in voter preferences—particularly the increasing preferences of blue-collar voters for progressive economic policies—have mitigated their defection from the Democratic Party. Absent these demand-side changes, voters’ partisan realignment would have been even more pronounced. Within specific policy domains, the environment emerges as the topic where parties diverge most in economic versus cultural emphasis: Democrats frame it culturally, while Republicans focus on economic aspects. Simulations reveal that a progressive, economically focused environmental policy would gain greater blue-collar voter support than a culturally focused one.
</div>



# Publications 

[Government Performance and Democracy: Survey Experimental Evidence from 12 Countries during Covid-19](BLMP.pdf), with [Michael Becher](https://www.ie.edu/university/about/faculty/michael-becher/), [Vincent Pons](https://www.vincentpons.org) et al., Forthcoming at the <em>Journal of Politics</em>.   <br />
&nbsp;&nbsp;&nbsp; Press: [The conversation](https://theconversation.com/es-la-democracia-el-chivo-expiatorio-de-la-pandemia-174253)

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
Crises of the magnitude of the Covid-19 pandemic may plausibly affect deep-seated attitudes of a large fraction of citizens. In particular, outcome-oriented theories imply that leaders' performance in response to such adverse events shapes people’s views about the government and about democracy. To assess these causal linkages empirically, we use a pre-registered survbey experiment covering 12 countries and 22,500 respondents during the pandemic. Our design enables us to leverage exogenous variation in evaluations of policies and leaders with an instrumental variables strategy. We find that people use information on both health and economic performance when evaluating the government. In turn, dissatisfaction with the government decreases satisfaction with how democracy works, but it does not increase support for non-democratic alternatives. The results suggests that comparatively bad government performance mainly spurs internal critiques of democracy. 
</div>

# Other Working Papers


 
 [“Compensate the Losers?” Economic policy preferences and partisan realignment in the US](KLMN.pdf), with [Ilyana Kuziemko](https://kuziemko.scholar.princeton.edu) and [Suresh Naidu](https://sites.santafe.edu/~snaidu/)., Reject and Resubmit at the <em>Quarterly Journal of Economics</em>.   <br />
 &nbsp;&nbsp;&nbsp; Press: [New York Times](https://www.nytimes.com/2023/11/06/opinion/democratic-party-inequality-biden.html?unlocked_article_code=1.8Uw.rkMU.dGuSoKAyAPBx&smid=url-share),
 [Washington Post](https://www.washingtonpost.com/business/2024/11/15/educational-divide-american-politics-trump/),
 [Pro Market](https://www.promarket.org/2024/02/26/how-the-democratic-party-lost-less-educated-voters/)
 
<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
We argue that the Democratic Party’s evolution on economic policy helps explain partisan realignment by education. We show that less-educated Americans differentially demand “predistribution” policies (e.g., a federal jobs guarantee, higher minimum wages, protectionism, and stronger unions), while more-educated Americans differentially favor redistribution (taxes and transfers). This educational gradient in policy preferences has been largely unchanged since the 1940s. We then show the Democrats’ supply of predistribution has declined since the 1970s. We tie this decline to the rise of a self-described "New Democrat" party faction who court more educated voters and are explicitly skeptical of predistribution. Consistent with this faction’s growing influence, we document the significant growth of donations from highly educated donors, especially from out-of-district, who play an increasingly important role in Democratic (especially ``New Democrat'') primary campaigns relative to Republican primaries. In response to these within-party changes in power, less-educated Americans began to leave the Democratic Party in the 1970s, after decades of serving as the party’s base. Roughly half of the total shift can be explained by their changing views of the parties’ economic policies. We also show that in the crucial transition period of the 1970s and 1980s, New Democrat-aligned candidates draw disproportionately from more-educated voters in both survey questions and actual Congressional elections.
</div>
 

[Investigating the Impact of Temperature Shocks on Income Disparity.](LM2024.pdf)  <br />
&nbsp;&nbsp;&nbsp;First 2021 Joseph Stiglitz Essay Prize of the [International Economic Association](https://www.iea-world.org). <br />

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
Most of the attention brought towards the uneven economic effects of climate change has been devoted to inequality between countries. This paper investigates how weather shocks affect income and inequality within a country. We measure the non-linear economic effects of weather shocks on the average level of income and the distribution of income in France combining French fiscal data with historical weather data from meteorological stations. Allowing for non-linear effects of weather, we are able to compute the marginal effect of weather shocks on income and inequality.
We find that days with an average temperature above 15 &deg; C start to have a detrimental effect on average income, with most significant effects located at the top of the distribution; an additional day above 30  &deg; C reduces the average household yearly income by 0.1%. This loss is equivalent to 34% of the average daily contribution to yearly income. I show that weather shocks increase within-country inequality in two distinct ways. Weather shocks increase between-areas inequality as poorer municipalities are more exposed to weather shocks than richer ones. In addition, these shocks also increase within-area inequality by hitting more hardly the lowest income deciles within each municipality. An additional day above 30  &deg; C increases the within-municipality D9/D1 inter-deciles ratio by 1.4 percentage point. 
We then use a Regional Climate Model to predict potential effects of global warming. Under business as usual scenarios, these effects would be equivalent to a yearly reduction in national income by 1 percentage point over the medium run and 2 percentage points for the last decades of the century, due to additional warm days. Finally, using Randomized Inference, we are able to assess the reliability of the results, controlling for any spurious spatial correlations.
</div>


[Non-linear Impacts of Climate Change on Income and Inequality in Viet Nam](LMEN.pdf), with Etienne Espagne and Ngo Duc Thanh, Revise and Resubmit at <em>World Development</em>.  <br />
&nbsp;&nbsp;&nbsp;Press: [The conversation](https://theconversation.com/inegalites-face-au-changement-climatique-la-balle-est-dans-le-camp-des-plus-riches-116616)

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
This paper measures the marginal impact of climate variability on Vietnamese households’ income. We combine survey data from the Viet Nam Household Living Standard Survey (VHLSS) database with daily climate data from the Climate Prediction Center to estimate the response function of Vietnamese households’ revenues to past climate variability. We focus on the non-linearity of the response and notably on the impacts of extremely warm days. We find that on average an additional day above 33°C is associated with a decrease of the yearly income by 1.3%. This strong effect is not specific to the agricultural sector. It is highest for the lowest deciles of the revenue distribution. Using projection scenarios under the Representation Concentration Pathways (RCP) 8.5 and 4.5, we find an estimated impact of global warming of up to 100% of households’ revenues in 2090 in some regions (Northern region and the Red River Delta area) under RCP8.5. These strong negative impacts are also likely to be specifically concentrated on poor households and to increase revenue inequalities.</div>


# Work in Progress
Climate Politics in the United States, with [Matilde Bombardini](https://matildebombardini.github.io), [Frederico Finan](https://eml.berkeley.edu//~ffinan/), [Suresh Naidu](https://sites.santafe.edu/~snaidu/), and [Francesco Trebbi](https://ftrebbi.com)


<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
We empirically study the effects of climate change and mitigation on U.S. politics. We combine new precinct-level voting data and Congressional candidate positions on environmental policy with high-resolution temperature and precipitation data and census-block-level estimates of "green" and "brown" employment shares. Holding politician positions fixed, we examine how vote shares for Democrats and Republicans respond to exogenous changes in local climate and green transition employment. An additional day with temperatures two standard deviations above the historical mean increases the Democratic vote margin by 0.08 to 0.47 percentage points, while a one-percentage-point decrease in brown jobs raises the Democratic vote share by 0.17 points. A comparable increase in green jobs raises Democratic vote shares by 0.45 points, although the estimates are imprecise. To address endogeneity in local job variations, we employ a shift-share design. Using these demand estimates, we incorporate the political supply of environmental policies into a model of political competition and estimate politician supply functions. Conditional on demand, we find that the same shocks at the district-year level shift candidate campaign ideology, pushing Republican candidates toward the center on climate issues and increasing pro-environment roll-call voting by winners. We then incorporate the demand and supply estimates into projections of future climate change and mitigation, outlining the political dynamics across different emission pathways.
</div>


Environmental Protection and Bureaucratic Oversight: Long-Run Economic and Ecological Impacts, with [Charles Taylor](https://ca-taylor.com/) and [David Szakonyi](https://davidszakonyi.com/)

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
Does bureaucratic variation in policy enforcement explain geographic disparities in development outcomes? This paper examines the role of Section 404 of the Clean Water Act, the key U.S. regulation governing land development in areas with aquatic resources. Focusing on the spatial variation in U.S. Army Corps district boundaries, which oversee the administration of the regulation, we find significant differences in the enforcement strictness of environmental rules. Leveraging a geographic discontinuity design and remote sensing land use data, we show that these inconsistencies have led to substantial divergences in development patterns across district borders since the late 1970s, with significant effects on housing expansion, wetland preservation, and flood risks. We evaluate the contribution of various mechanisms, such as local characteristics of district headquarters, political orientation of district head, and potential corruption, in driving these outcomes. We discuss the broader implications of these findings for policy design and environmental governance. Given Section 404's central role in regulating both economic activity and environmental conservation, our results raise important concerns about the uneven administration of federal law and its potential consequences for development and environmental outcomes.
</div>



The Polarization of State Legislatures? Evidence from State Statutes, with [Charles Angelucci](https://sites.google.com/site/charlesangelucci/) and [Elliott Ash](https://elliottash.com)

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
This paper analyzes the adoption and diffusion of legislation enacted by U.S. States since 1800. We use a large language model to extract and summarize the policy content of 2.5 million statutes, from which we construct measures of similarity and diffusion. We find that states with greater geographic, economic and political similarity implement more similar policies. Consistent with an important component for local preferences in state policies on social issues, the social policy preferences of state residents (but not economic policy preferences) are increasingly determinative of enacted policies. Consistent with increasing nationalization of economic policies, federal legislative texts have become increasingly influential on state legislative texts in laws about the economy. State legislatures with similar partisan compositions used to produce more alike legislation, but that similarity in legislative texts has decreased recently despite continued partisan alignment across those legislatures. Lastly, we classify all policies into 2,048 clusters and document patterns of innovation and diffusion of these policies.
</div>


Ownership, Advertising and Content Choice in the News Media, with [Pierre Bodéré](https://pierrebodere.github.io) and [Marguerite Obolensky](http://margueriteobolensky.github.io/)<br>

<p style="margin-top: -15px">
    <button class="abstract-btn">Abstract</button>
</p>
<div class="abstract-content">
The rise in political polarization over the recent years has fostered scrutiny of the structure of the news industry’ s influence on political outcomes. How should policymakers regulate news producers when they value news diversity and large publishers shape the ideological landscape? To answer this question, we develop an empirical model of competition for readership and advertisers between news producers. We recover the topic content and ideological positions of 200 major U.S. daily newspapers using recent advances in Natural Language Processing on millions of published articles. We find that over the period 2007-2017, the median newspaper in our sample got closer to the ideology of the Democratic party. Second, we embed these topics and ideal points in a demand model for differentiated products with heterogeneous readers. Our model shows that rich readers lean democrat and consume more news about social and political questions while the elderly are more conservative and care more about local news. Using the estimated demand model and data on advertising contracts and readership, we can recover the cost of producing each type of content. Given this model of news supply, we intend to use our framework to provide recommendations on antitrust rules weighing both consumer welfare and ideological diversity.
</div>

Do Policies Change Politics? The Political Effects of Minimum Wage Increases, with [Ethan Kaplan](https://www.econ.umd.edu/facultyprofile/kaplan/ethan), [Suresh Naidu](https://sites.santafe.edu/~snaidu/), and [Aaron Schein](https://www.aaronschein.com)<br>



<style>
/* Style the abstract button to look like a hyperlink */
.abstract-btn {
    color: rgba(0, 49, 60, 1); /* Default hyperlink color */
    cursor: pointer; /* Pointer/hand icon */
    text-decoration: underline !important; /* Underline text */
    font-size: 16px; /* Font size */
    background: none; /* No background */
    border: none; /* No border */
    padding: 0; /* No padding */
    font-family: inherit; /* Inherit font settings */
    display: inline-block; /* Add this line */
    text-decoration-style: solid !important; /* Set underline style */
    text-decoration-color: rgba(150, 150, 150, 1) !important; /* Light grey color for underline */
}


/* Change text color on hover */
.abstract-btn:hover {
    color: rgba(0, 49, 60, 0.4); /* Hover color */
    text-decoration: underline; /* Ensure underline on hover */
}

/* Style the abstract content */
.abstract-content {
    margin-top: 10px; /* Some space above the abstract content */
    padding: 10px; /* Some padding */
    border: none; /* Remove border */
    background-color: transparent; /* Remove background color */
    font-size: 14px; /* Adjust the font size to your preference */
    display: none; /* Hide the abstract content initially */
    text-align: justify; /* Justify the text */
}
</style>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var buttons = document.querySelectorAll('.abstract-btn');
    buttons.forEach(function(button) {
        button.addEventListener('click', function() {
            var abstract = button.parentElement.nextElementSibling;
            if (abstract.style.display === 'none' || abstract.style.display === '') {
                abstract.style.display = 'block';
            } else {
                abstract.style.display = 'none';
            }
        });
    });
});
</script>
